# Generated by Django 5.1.6 on 2025-03-18 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This category already exists.'}, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Office Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeMassOutgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_mass_outgoings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'office_mass_outgoing',
            },
        ),
        migrations.CreateModel(
            name='OfficeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office_supplies.officecategory')),
            ],
            options={
                'verbose_name_plural': 'Office Supplies',
            },
        ),
        migrations.CreateModel(
            name='OfficeMassOutgoingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('mass_outgoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_items', to='office_supplies.officemassoutgoing')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_items', to='office_supplies.officesupply')),
            ],
            options={
                'db_table': 'office_mass_outgoing_items',
            },
        ),
        migrations.AddField(
            model_name='officemassoutgoing',
            name='supplies',
            field=models.ManyToManyField(related_name='mass_outgoing_transactions', through='office_supplies.OfficeMassOutgoingItem', to='office_supplies.officesupply'),
        ),
    ]
