# Generated by Django 5.1.6 on 2025-03-18 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_supplies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeMassIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('items', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_mass_incoming', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mass Incoming Record',
                'verbose_name_plural': 'Mass Incoming Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
