# Generated by Django 5.1.6 on 2025-03-24 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('previous_quantity', models.IntegerField(default=0)),
                ('current_quantity', models.IntegerField(default=0)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_items', models.IntegerField()),
                ('low_stock_items', models.IntegerField()),
                ('expiring_soon_items', models.IntegerField()),
                ('supply_type', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('date', 'supply_type')},
            },
        ),
    ]
