# Generated by Django 5.1.6 on 2025-03-18 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This category already exists.'}, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('alert_threshold', models.PositiveIntegerField(default=0, help_text='Minimum quantity to trigger alerts (0 to disable)')),
            ],
            options={
                'verbose_name_plural': 'Vet Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MassOutgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('patient_name', models.CharField(blank=True, default='', max_length=200)),
                ('doctor_name', models.CharField(blank=True, default='', max_length=200)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_mass_outgoings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VetSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='vet_supplies.vetcategory')),
            ],
            options={
                'verbose_name_plural': 'Vet Supplies',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_supplies.vetsupply')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('expiring', 'Expiring Soon'), ('expired', 'Expired'), ('out_of_stock', 'Out of Stock')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_notifications', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vet_supplies.vetsupply')),
            ],
            options={
                'verbose_name': 'Inventory Notification',
                'verbose_name_plural': 'Inventory Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassOutgoingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient_name', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_supplies.vetsupply')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MassOutgoingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('mass_outgoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vet_supplies.massoutgoing')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_supply_transactions', to='vet_supplies.vetsupply')),
            ],
        ),
        migrations.AddField(
            model_name='massoutgoing',
            name='supplies',
            field=models.ManyToManyField(related_name='vet_outgoing_transactions', through='vet_supplies.MassOutgoingItem', to='vet_supplies.vetsupply'),
        ),
        migrations.CreateModel(
            name='ExpiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_supplies.vetsupply')),
            ],
        ),
        migrations.CreateModel(
            name='VetSupplyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet_supplies.officecategory')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='vet_supplies_quantity_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='vetsupply',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='vet_supply_quantity_positive'),
        ),
    ]
