# Generated by Django 5.1.6 on 2025-03-21 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0002_transactionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massoutgoingtransaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='massoutgoingtransaction',
            name='supply',
        ),
        migrations.AddField(
            model_name='massoutgoingtransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massoutgoingtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='massoutgoingtransaction',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='massoutgoingtransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='massoutgoingtransaction',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='massoutgoingtransaction',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='MassOutgoingTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vet_supplies.vetsupply')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vet_supplies.massoutgoingtransaction')),
            ],
        ),
    ]
