# Generated by Django 5.1.6 on 2025-03-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0004_alter_massoutgoingtransaction_processed_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
