# Generated by Django 5.1.6 on 2025-03-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_supplies', '0005_delete_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massoutgoingitem',
            name='mass_outgoing',
        ),
        migrations.RemoveField(
            model_name='massoutgoingitem',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='massoutgoingtransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='massoutgoingtransactionitem',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='massoutgoingtransactionitem',
            name='supply',
        ),
        migrations.DeleteModel(
            name='MassOutgoing',
        ),
        migrations.DeleteModel(
            name='MassOutgoingItem',
        ),
        migrations.DeleteModel(
            name='MassOutgoingTransaction',
        ),
        migrations.DeleteModel(
            name='MassOutgoingTransactionItem',
        ),
    ]
